#!/bin/bash -e

# This shell script is used by .travis.yml and the makefile to run the proc
# test suite twice (once as a regular user and once with root privileges) in
# order to get the maximum test coverage:
#
#  - The proc.core.Process.exe_path and proc.core.Process.exe_name fall back
#    methods are only required for regular users because with root privileges
#    proc.core.Process.exe is always available.
#
#  - The proc.apache module requires root privileges to identify WSGI workers,
#    again because of the proc.core.Process.exe property.

# Try to kill any running gpg-agents, to give the test suite the chance to spawn a new one.
killall gpg-agent &>/dev/null || true

# First we run the test suite as a regular user.
py.test --cov

# Again we try to kill any running gpg-agents to give the test suite the chance to spawn a new one.
sudo killall gpg-agent &>/dev/null || true

# Then we run the test suite with root privileges.
sudo $(which py.test) --cov --cov-append

# Restore the ownership of the coverage data.
sudo chown $USER:$USER .coverage

# Report the coverage statistics to the terminal
# and fail if the coverage drops below 90%.
coverage report --fail-under=90
